export const FETCH_AUTHORS_START = "AUTHORS/FETCH_AUTHORS_START" as const;
export const FETCH_AUTHORS_SUCCEED = "AUTHORS/FETCH_AUTHORS_SUCCEED" as const;
export const FETCH_AUTHORS_FAIL = "AUTHORS/FETCH_AUTHORS_FAIL" as const;
